// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimescaleAPI.Infrastructure;

#nullable disable

namespace TimescaleAPI.Migrations
{
    [DbContext(typeof(MetricsContext))]
    [Migration("20260723150213_UpdateColumnNames")]
    partial class UpdateColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Origin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Origins");
                });

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgValue")
                        .HasColumnType("double precision");

                    b.Property<int>("DeltaDate")
                        .HasColumnType("integer");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<double>("IndicatorValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Result", b =>
                {
                    b.HasOne("TimescaleAPI.Infrastructure.Models.Origin", "Origin")
                        .WithMany("Results")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Value", b =>
                {
                    b.HasOne("TimescaleAPI.Infrastructure.Models.Origin", "Origin")
                        .WithMany("Values")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("TimescaleAPI.Infrastructure.Models.Origin", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
